name: owon_pct513
description: A new Flutter application for pct513 device

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^3.0.0
  fluttertoast: ^3.1.3
  flutter_easyrefresh: ^2.0.4
  provider: ^3.1.0
  mqtt_client: ^5.5.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.14.4
  flutter_spinkit: ^4.0.0
  url_launcher: ^5.4.1
  sqflite: 1.1.7
  progress_dialog: ^1.2.0
  connectivity: ^0.4.6+1
  common_utils: ^1.1.3
  cookie_jar: ^1.0.1
  flutter_screenutil: ^0.7.0
  shared_preferences: ^0.5.4+8
  package_info: ^0.4.0+12
  flutter_slidable: ^0.5.4
  permission_handler: ^4.0.0
  flutter_native_timezone: ^1.0.4
  cool_ui: ^0.3.1
  flutter_picker: ^1.1.0
  infinite_listview: ^1.0.1+1
#  google_maps_flutter: ^0.5.21
#  firebase_core: 0.4.0
#  cloud_firestore: ^0.12.10

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/launch_bg.png
    - assets/images/launch_icon.png
    - assets/images/modifyPsw.svg
    #login
    - assets/images/login/confirm_psw_icon.svg
    - assets/images/login/login_bg_center_left_bottom.png
    - assets/images/login/login_bg_right_top.png
    - assets/images/login/login_bg_smail_icon.png
    - assets/images/login/login_forgot_psw_icon.svg
    - assets/images/login/login_register_icon.svg
    - assets/images/login/new_psw_icon.svg
    - assets/images/login/password_icon.svg
    - assets/images/login/register_header_icon.png
    - assets/images/login/register_psw_register_icon.svg
    - assets/images/login/reset_psw_confirm_icon.svg
    - assets/images/login/reset_psw_header_icon.png
    - assets/images/login/username_icon.svg
    - assets/images/login/verify_psw_code_icon.svg

    - assets/images/list_set/pct_icon@3x.png
    - assets/images/list_set/warn_black.svg

    - assets/images/list_set/set_sel_black@3x.png
    - assets/images/list_set/set_sel_white@3x.png
    - assets/images/list_set/the_sel_black@3x.png
    - assets/images/list_set/the_sel_white@3x.png

    - assets/images/list_set/set_unsel_black@3x.png
    - assets/images/list_set/set_unsel_white@3x.png
    - assets/images/list_set/the_unsel_black@3x.png
    - assets/images/list_set/the_unsel_white@3x.png

    - assets/images/appearance/appear_black.png
    - assets/images/appearance/appear_white.png
    - assets/images/appearance/appear_icon.png

    - assets/images/list_set/set_modifyPsw_b.png
    - assets/images/list_set/set_modifyPsw_w.png
    - assets/images/list_set/set_about_b.png
    - assets/images/list_set/set_about_w.png
    - assets/images/list_set/set_appear_b.png
    - assets/images/list_set/set_appear_w.png
    - assets/images/list_set/set_help_b.png
    - assets/images/list_set/set_help_w.png
    - assets/images/list_set/set_map_b.png
    - assets/images/list_set/set_map_w.png
    - assets/images/list_set/set_exit.png

    - assets/images/management/m_humi_water.svg
    - assets/images/management/m_confort_away.svg
    - assets/images/management/m_confort_home.svg

    - assets/images/management/m_fan_auto.svg
    - assets/images/management/m_fan_circle.svg
    - assets/images/management/m_fan_show.svg

    - assets/images/management/m_hold_permHold.svg
    - assets/images/management/m_hold_schedule.svg
    - assets/images/management/m_hold_tempHold.svg

    - assets/images/management/m_sys_auto.svg
    - assets/images/management/m_sys_cool.svg
    - assets/images/management/m_sys_eHeat.svg
    - assets/images/management/m_sys_heat.svg
    - assets/images/management/m_sys_off.svg


    - assets/images/device_set/dset_cirSetting_b.png
    - assets/images/device_set/dset_cirSetting_w.png
    - assets/images/device_set/dset_devInfo_b.png
    - assets/images/device_set/dset_devInfo_w.png
    - assets/images/device_set/dset_rename_b.png
    - assets/images/device_set/dset_rename_w.png
    - assets/images/device_set/dset_sensorSetting_b.png
    - assets/images/device_set/dset_sensorSetting_w.png
    - assets/images/device_set/dset_temSetting_b.png
    - assets/images/device_set/dset_temSetting_w.png
    - assets/images/device_set/dset_vacSetting_b.png
    - assets/images/device_set/dset_vacSetting_w.png
    - assets/images/device_set/vac_depart_b.png
    - assets/images/device_set/vac_depart_w.png
    - assets/images/device_set/vac_return_b.png
    - assets/images/device_set/vac_return_w.png
    - assets/images/device_set/vac_vacationSetting_b.png
    - assets/images/device_set/vac_vacationSetting_w.png
    - assets/images/device_set/vac_noSetting_b.png
    - assets/images/device_set/vac_return.svg
    - assets/images/device_set/vac_depart.svg
    - assets/images/device_set/vac_set.svg

    - assets/images/device_set/schedule/schedule_copy.svg
    - assets/images/device_set/schedule/schedule_copy_no_select.svg
    - assets/images/device_set/schedule/schedule_copy_select.svg
    - assets/images/device_set/schedule/schedule_disabled.png
    - assets/images/device_set/schedule/schedule_mode_away.svg
    - assets/images/device_set/schedule/schedule_mode_home.svg
    - assets/images/device_set/schedule/schedule_mode_sleep.svg
    - assets/images/device_set/schedule/schedule_mode_wake.svg
    - assets/images/device_set/schedule/schedule_setting_copy.png
    - assets/images/device_set/schedule/schedule_setting_mode_away.png
    - assets/images/device_set/schedule/schedule_setting_mode_home.png
    - assets/images/device_set/schedule/schedule_setting_mode_sleep.png
    - assets/images/device_set/schedule/schedule_setting_mode_wake.png
    - assets/images/device_set/schedule/schedule_time_icon.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: PINGFANG
#      fonts:
#        - asset: assets/fonts/PINGFANG-BOLD.TTF
#        - asset: assets/fonts/PINGFANG-EXTRALIGHT.TTF
#        - asset: assets/fonts/PINGFANG-HEAVY.TTF
#        - asset: assets/fonts/PINGFANG-LIGHT.TTF
#        - asset: assets/fonts/PINGFANG-MEDIUM.TTF
#        - asset: assets/fonts/PINGFANG-REGULAR.TTF
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
